<?xml version="1.0" encoding="utf-8"?><Database Name="dmaa0915_2Sem_4" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=kraka.ucn.dk;Initial Catalog=dmaa0915_2Sem_4;Persist Security Info=True;User ID=dmaa0915_2Sem_4" SettingsObjectName="ConsoleApplication1.Properties.Settings" SettingsPropertyName="dmaa0915_2Sem_4ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[Table]" Member="Hejsas">
    <Type Name="Hejsa">
      <Column Name="Id" Member="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>